[versions]
# MavenPublish
vanniktech-maven-publish = "0.28.0"
# Kotlin
kotlin = "2.0.0"
# KotlinX
kotlinx-collections-immutable = "0.3.7"
kotlinx-datetime = "0.6.0"
kotlinx-serialization-json = "1.7.0-RC"
kotlinx-coroutines = "1.9.0-RC"
# Google
google-devtools-ksp = "2.0.0-1.0.22"
google-gson = "2.11.0"
# Squareup
squareup-kotlinpoet = "1.17.0"
squareup-moshi = "1.15.1"
# FasterXML
fasterxml-jackson = "2.17.1"
[libraries]
# Kotlin
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
# KotlinX
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
# Google
google-devtools-ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "google-devtools-ksp" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "google-gson" }
# Squareup
squareup-kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "squareup-kotlinpoet" }
squareup-moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "squareup-moshi" }
# FasterXML
fasterxml-jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "fasterxml-jackson" }
[bundles]
kotlinx = ["kotlinx-collections-immutable", "kotlinx-datetime", "kotlinx-serialization-json", "kotlinx-coroutines-core"]
foundation-codegen = ["kotlinx-serialization-json", "google-devtools-ksp", "squareup-kotlinpoet-ksp"]
[plugins]
# Custom Plugins
cleanwizard = { id = "corp.tbm.cleanwizard", version = "1.0.0" }
cleanarchitecturemapper-kotlin = { id = "corp.tbm.cleanarchitecturemapper.kotlin" }
cleanarchitecturemapper-codegen-foundation = { id = "corp.tbm.cleanarchitecturemapper.codegen.foundation" }
cleanarchitecturemapper-codegen-visitor = { id = "corp.tbm.cleanarchitecturemapper.codegen.visitor" }
cleanarchitecturemapper-workload = { id = "corp.tbm.cleanarchitecturemapper.workload" }
# MavenPublish
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
# Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
# KSP
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "google-devtools-ksp" }